<<<<<<< HEAD
[tool.isort]
profile = "black"
line_length = 79

[tool.black]
line-length = 79
=======
[tool.isort]
profile = "black"
line_length = 79

[tool.black]
line-length = 79
>>>>>>> 9eade0cc3adcbe53f013dc223292e6100cb81cc3
